---
title: "SimulationExample"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(VARgrowth)
library(splines)
library(mvtnorm)
library(dplyr)
library(ggplot2)
library(nlme)
library(rstan)
library(bayesplot)
library(brms)
```


```{r fit model}
data <- readRDS("./SimData.RDS")
nchains = 4
iter = 5000
warmup = 0.5*iter
seed = 123123
ctrl <- list(adapt_delta = 0.9)

fit_model <- function(data, 
                      nchains, 
                      iter, 
                      warmup, 
                      seed,
                      ctrl){
  ### FOR NOW: growth function and theta transform are fixed
  GrowthFunction <- GompertzFunction()
  numMeanParams <- GrowthFunction$num_params
  totalGroups <- length(unique(train_data$group))

  pTheta <- PriorTheta(rep(list(NoPrior()), numMeanParams),
                     priorParam1 = matrix(0, nrow = totalGroups, ncol = numMeanParams), 
                     priorParam2 = matrix(0, nrow = totalGroups, ncol = numMeanParams))
  pObsVar <- PriorObsVar(list(NormalPrior()),
                       priorParam1 = 2,
                       priorParam2 = 2)
  pBeta <- PriorBetaTheta(list(NormalPrior()),
               priorParam1 = matrix(0, ncol(XTheta), numMeanParams),
               priorParam2 = matrix(5, ncol(XTheta), numMeanParams))

  pSigmaTheta <- PriorSigmaTheta(rep(list(NormalPrior()), numMeanParams),
                         priorParam1 = rep(0, numMeanParams),
                         priorParam2 = rep(100, numMeanParams))

  PriorList <- list(pTheta,
                    pObsVar,
                    pBeta,
                    pSigmaTheta)

  ThetaTransform <- ThetaTransformations(list(logTransform,
                                              logTransform,
                                              logitTransform),
                                         inverse = FALSE)
  
  ### model 1: intercept model
  ThetaTrend <- LinearModelTrend(data, ~ 1)
  ### reduce to just post mean, post median, credible interval, sampler errors
  tryCatch(
    {fit <- VARGrowth(data,
                 ThetaTrend_model, 
                 GrowthFunction, 
                 PriorList, 
                 ThetaTransform,
                 nchains = nchains,
                 cores = nchains,
                 control = ctrl,
                 iter = iter,
                 warmup = warmup,
                 seed = seed,
                 pars = c("marg_log_lik_samp", "theta_samp",
                          "mu_temp"),
                 include = FALSE)
    },
    error = function(e){
      fit <- NA
    }
  )
  
}

```

```{r do fit}
data <- readRDS("./SimData.RDS")
fits <- lapply(data, 
               fit_model,
               )

```


